version: "3.9"
services:
  app:
    image: vesnam/java-multi-stage
    container_name: java-multi-stage
    ports:
      - '8081:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - logvolume02:/var/log
volumes:
  logvolume02: {}
